### ISSUE TITLE
[Feature Request] usability issue with Ins button and File menu for New tasks 

### ISSUE THREAD

**Issue by damascene** [QTodoTxt/QTodoTxt#159]
This is really great project that helped me favor it over other softwares and systems.
I think having the Ins button as a shortcut for inserting new task is not a very good idea. It's not easy to reach on every keyboard without moving hands out of typing position.
On my keyboard it's the third from top right.

That makes me favor using the mouse for inserting new tasks but again I hit new from the file menu instead of the Edit and I get a new todo.txt file instead of a new tasks.

What I suggest is having file menu >> new (shortcut: CTRL+N) create a new tasks and but new file as another choice (Tomboy concept is a a good example)

**Comment by kmicc** [comment]
Ctrl-N is already working (besides INS) for creating new tasks (never used it, because I personally find the INS-key more handy). I don't think we should give up the separation between "File" and "Task" in the main menu. Furthermore it is suggested to add a toolbar (https://github.com/mNantern/QTodoTxt/pull/151) and a context menu (https://github.com/mNantern/QTodoTxt/issues/107), so I don't see the need to do anything here.
