### ISSUE TITLE
Add Notes to tasks

### ISSUE THREAD

**Issue by Kerm** [QTodoTxt/QTodoTxt#385]
Hello,
I realy like the QTodoText Project so far!

But how stressful would it be, to add some kind of notes field to a task?
I think there is already an add on on the CLI project. 

thanks in advance.
regards

**Comment by oroulet** [comment]
that is hard, but not impossible for someone motivated

**Comment by topas-rec** [comment]
As a workaround you can use external notes and link them inside a task (hyperlink).
(I personally would prefer this method because it divides tasks and notes - which I think is good)
This has the advantage, that you can use a dedicated editor for the notes. Notes don't necessarily have to be text. It can be a structured word file or a picture/drawing.
For this one should be able to link notes using a relative path. One can cord l copy the whole directory with the todo and the notes to another PC or cloud.

On 23 January 2017 11:14:53 CET, Kerm <notifications@github.com> wrote:
>Hello,
>I realy like the QTodoText Project so far!
>
>But how stressful would it be, to add some kind of notes field to a
>task?
>I think there is already an add on on the CLI project. 
>
>thanks in advance.
>regards
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/QTodoTxt/QTodoTxt/issues/385

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by oroulet** [comment]
@topas-rec good point!

**Comment by topas-rec** [comment]
To make it easier for the user we could add a button that opens a file selection menu and adds the selected file (s?) As link to the task.

**Comment by Kerm** [comment]
Wow, what a great community!
Thx for the fast reply!

I really like the hyperlink idea, will try it out tomorrow @work.

Would some kind of "create new .txt" or something like that be possible so the the hyperlink will be set automatically and I could directly type the note?

regards

**Comment by oroulet** [comment]
Sounds like an easy and good idea

**Comment by Kerm** [comment]
I just tried to set an hyperlink with <a href="C:\Notes\note.txt">Note 1</a> but nothing is happening when clicking it. Am I missing something?

**Comment by topas-rec** [comment]
With internet links you don't have to worry about the HTML markup like <a href> and so on.
Just enter the link.
With local files try to prepend file:/// Anne append link without quotes.
Full link example: file:///C:\test.text
(For windows)

BTW this should be done easier.

**Comment by oroulet** [comment]
links are broken in master. if you use a release it will work. Now I need to find out why it is broken, it is the QStyledItemDelegate stuff that breaks hyperlinks....

**Comment by oroulet** [comment]
https://github.com/QTodoTxt/QTodoTxt/pull/387
missing icon and use wrong dialog but show the idea

**Comment by PKEv** [comment]
If you do then it is up to make a link like 
```
<a href=file:/full_path> file </a>
```
but although the link will look good, its use is currently not possible
![default](https://cloud.githubusercontent.com/assets/6053197/22266309/a22b5bbc-e290-11e6-81c6-84a0d45a3cdf.PNG)
