### ISSUE TITLE
new extensions - Recurrence

### ISSUE THREAD

**Issue by mimmori** [QTodoTxt/QTodoTxt#86]
It would be great to have the recurrence extension like simpletask for android!
(https://github.com/bram85/todo.txt-tools/wiki/Recurrence)

**Comment by mimmori** [comment]
anyone interested?

**Comment by funkyfuture** [comment]
yeah, i actually wanted to implement this when my (redesign of the `Task`-class)[https://github.com/funkyfuture/QTodoTxt/tree/lib-task] is finished and merged.

**Comment by aurisnoctis** [comment]
+1 for both -- recurrence, and the suggested implementation as in Simpletask, storing the information about recurrence within the todo.txt file (instead of a separate file as done by todo.txt-cli add-ons so far)

Thanks to all who contribute to this software. And sorry again for duplicating, still wondering why my issue search for 'recur' didn't bring up this entry.
